package com.localadb.manager.adb

enum class OptimizationRisk { LOW, MEDIUM }

data class OptimizableApp(
    val displayName: String,
    val packageName: String,
    val description: String,
    val risk: OptimizationRisk,
    val isPriority: Boolean = false,
)

data class ManufacturerProfile(
    val name: String,
    val emoji: String,
    val apps: List<OptimizableApp>,
)

// Вспомогательная функция для краткости
private fun p(
    name: String, pkg: String, desc: String,
    risk: OptimizationRisk = OptimizationRisk.LOW,
    priority: Boolean = false,
) = OptimizableApp(name, pkg, desc, risk, priority)

val OPTIMIZATION_DATABASE: List<ManufacturerProfile> = listOf(

    // ─────────────────────────────────────────────
    // GOOGLE (универсальный, для любого устройства)
    // ─────────────────────────────────────────────
    ManufacturerProfile("Google (любое устройство)", "🌐", listOf(
        p("Digital Wellbeing", "com.google.android.apps.wellbeing",
            "Трекер экранного времени — постоянно работает в фоне и собирает данные об использовании",
            OptimizationRisk.LOW, priority = true),
        p("Google TV", "com.google.android.videos",
            "Стриминговый видеосервис Google — предустановлен на большинстве Android",
            OptimizationRisk.LOW, priority = true),
        p("Google Podcasts", "com.google.android.apps.podcasts",
            "Подкасты Google — прекращён, но остаётся предустановленным",
            OptimizationRisk.LOW, priority = true),
        p("Google News", "com.google.android.apps.magazines",
            "Новостная лента Google с рекламой и трекингом интересов",
            OptimizationRisk.LOW, priority = true),
        p("Android Auto", "com.google.android.projection.gearhead",
            "Интерфейс для автомобильных экранов — бесполезен без совместимого авто",
            OptimizationRisk.LOW, priority = true),
        p("Google One", "com.google.android.apps.subscriptions.red",
            "Менеджер подписки на облачное хранилище Google One",
            OptimizationRisk.LOW, priority = true),
        p("Google Assistant", "com.google.android.googlequicksearchbox",
            "Голосовой помощник Google — тяжёлый фоновый сервис",
            OptimizationRisk.MEDIUM),
        p("Google Meet", "com.google.android.apps.tachyon",
            "Видеозвонки Google Meet", OptimizationRisk.LOW),
        p("Google Keep", "com.google.android.keep",
            "Заметки Google Keep", OptimizationRisk.LOW),
        p("Google Fit", "com.google.android.apps.fitness",
            "Трекер здоровья и активности Google", OptimizationRisk.LOW),
        p("Google Files", "com.google.android.apps.nbu.files",
            "Файловый менеджер Google", OptimizationRisk.LOW),
        p("Google Lens", "com.google.ar.lens",
            "AR-распознавание объектов через камеру", OptimizationRisk.LOW),
        p("Google Wallpapers", "com.google.android.apps.wallpaper",
            "Приложение обоев Google с онлайн-подборкой", OptimizationRisk.LOW),
        p("Duo (старый Meet)", "com.google.android.apps.duo",
            "Устаревшее приложение видеозвонков, заменено на Meet", OptimizationRisk.LOW),
        p("Google Feedback", "com.google.android.feedback",
            "Отправка отчётов об ошибках в Google", OptimizationRisk.LOW),
    )),

    // ─────────────────
    // XIAOMI / REDMI / POCO
    // ─────────────────
    ManufacturerProfile("Xiaomi / Redmi / POCO", "📱", listOf(
        p("MSA (реклама MIUI)", "com.miui.msa.global",
            "Рекламный движок MIUI — показывает рекламу в системных приложениях",
            priority = true),
        p("MIUI Analytics", "com.miui.analytics",
            "Сбор и отправка аналитики использования устройства в Xiaomi",
            priority = true),
        p("MIUI Daemon", "com.miui.daemon",
            "Фоновый демон сбора диагностических данных",
            OptimizationRisk.MEDIUM, priority = true),
        p("Ad Solution", "com.miui.systemAdSolution",
            "Системный рекламный SDK — источник рекламы в MIUI",
            priority = true),
        p("GetApps", "com.xiaomi.market",
            "Магазин приложений Xiaomi", priority = true),
        p("App Vault", "com.miui.personalassistant",
            "Лента рекомендаций на левом рабочем столе", priority = true),
        p("Joyose", "com.xiaomi.joyose",
            "Рекламный сервис для игр от Xiaomi", priority = true),
        p("Bug Report / Feedback", "com.miui.bugreport",
            "Отправка отчётов об ошибках в Xiaomi", priority = true),
        p("User Experience Program", "com.miui.systemAdSolution",
            "Программа сбора данных об использовании для улучшения продуктов",
            priority = true),
        p("Mi Browser", "com.mi.globalbrowser",
            "Встроенный браузер Xiaomi с трекингом"),
        p("Mi Video", "com.miui.video",
            "Видеоплеер Xiaomi с рекламой"),
        p("Mi Music", "com.miui.player",
            "Музыкальный плеер Xiaomi"),
        p("Mi Credit", "com.xiaomi.finance",
            "Финансовые услуги Xiaomi (кредиты, страховки)"),
        p("Yellow Pages", "com.miui.yellowpage",
            "Определитель номеров Xiaomi"),
        p("Mi Share", "com.miui.mishare.connectivity",
            "Беспроводная передача файлов между устройствами Xiaomi"),
        p("Wallpaper Carousel", "com.miui.miwallpaper",
            "Автоматическая смена обоев рабочего стола"),
        p("Security Analytics", "com.miui.securitycenter.remote",
            "Отправка данных об использовании приложения «Безопасность»"),
        p("MiPush SDK", "com.xiaomi.mipush.sdk",
            "Push-уведомления от сервисов Xiaomi",
            OptimizationRisk.MEDIUM),
        p("Mi Cloud", "com.miui.cloudservice",
            "Облачный сервис Xiaomi",
            OptimizationRisk.MEDIUM),
        p("Mi Cloud Backup", "com.miui.cloudbackup",
            "Резервное копирование в облако Xiaomi",
            OptimizationRisk.MEDIUM),
        p("Mi Drop (передача файлов)", "com.xiaomi.midrop",
            "Передача файлов между устройствами Xiaomi через Wi-Fi Direct"),
        p("Cleaner", "com.miui.cleanmaster",
            "Очиститель памяти MIUI"),
        p("Scanner", "com.xiaomi.scanner",
            "QR-сканер Xiaomi"),
        p("GetApps Updater", "com.xiaomi.mipicks",
            "Рекомендации и обновления из GetApps"),
        p("Mi AI", "com.miui.voiceassist",
            "Голосовой ассистент Xiaomi"),
        p("Mi Pay", "com.mipay.wallet",
            "Платёжный сервис Xiaomi Mi Pay"),
        p("Themes", "com.android.thememanager",
            "Магазин тем MIUI",
            OptimizationRisk.MEDIUM),
        p("Notes Sync", "com.miui.notes",
            "Синхронизация заметок с Mi Cloud",
            OptimizationRisk.MEDIUM),
    )),

    // ─────────────────
    // SAMSUNG
    // ─────────────────
    ManufacturerProfile("Samsung", "🌀", listOf(
        p("Bixby Voice", "com.samsung.android.bixby.agent",
            "Голосовой ассистент Bixby — тяжёлый фоновый сервис",
            OptimizationRisk.MEDIUM, priority = true),
        p("Bixby Routines", "com.samsung.android.app.routines",
            "Автоматические сценарии Bixby по расписанию",
            OptimizationRisk.MEDIUM, priority = true),
        p("Bixby Vision", "com.samsung.android.bixbyvision.framework",
            "AR-распознавание объектов через камеру Bixby",
            priority = true),
        p("Samsung Free", "com.samsung.android.app.spage",
            "Новостная лента Samsung с рекламой (левый экран рабочего стола)",
            priority = true),
        p("Smart Tutor", "com.rsupport.rs.activity.samsung",
            "Удалённое управление устройством сотрудниками Samsung",
            priority = true),
        p("Samsung Global Goals", "com.samsung.android.globalgoals",
            "Показывает рекламу между разблокировками в благотворительных целях",
            priority = true),
        p("Samsung Push Service", "com.sec.spp.push",
            "Push-уведомления от сервисов Samsung",
            OptimizationRisk.MEDIUM, priority = true),
        p("Samsung Analytics", "com.samsung.android.memorymanager",
            "Фоновый сбор данных об использовании устройства Samsung",
            priority = true),
        p("Galaxy Store", "com.sec.android.app.samsungapps",
            "Магазин приложений Samsung"),
        p("Game Launcher", "com.samsung.android.game.gamehome",
            "Игровой центр Samsung"),
        p("Game Booster", "com.samsung.android.game.gametools",
            "Оверлей с инструментами поверх игр"),
        p("AR Zone", "com.samsung.android.arzone",
            "AR Emoji и зарисовки дополненной реальности"),
        p("Samsung Members", "com.samsung.android.voc",
            "Обратная связь и поддержка Samsung"),
        p("Samsung Tips", "com.samsung.android.app.tips",
            "Советы по использованию устройства"),
        p("Samsung Checkout", "com.sec.android.app.billing",
            "Система оплаты внутри Galaxy Store"),
        p("Samsung Visit In", "com.samsung.android.widgetapp.webmanual",
            "Интерактивное руководство пользователя"),
        p("Samsung Cloud", "com.samsung.android.scloud",
            "Облачный сервис Samsung",
            OptimizationRisk.MEDIUM),
        p("Samsung Pass", "com.samsung.android.samsungpass",
            "Менеджер паролей Samsung Pass",
            OptimizationRisk.MEDIUM),
        p("Samsung Pay", "com.samsung.android.spay",
            "Платёжный сервис Samsung Pay",
            OptimizationRisk.MEDIUM),
        p("Samsung Health", "com.sec.android.app.shealth",
            "Трекер здоровья и активности Samsung",
            OptimizationRisk.MEDIUM),
        p("Samsung Internet", "com.sec.android.app.sbrowser",
            "Браузер Samsung"),
        p("Samsung Themes", "com.samsung.android.themestore",
            "Магазин тем оформления Samsung"),
        p("Samsung Reminder", "com.samsung.android.app.reminder",
            "Напоминания Samsung (отдельно от стандартных)"),
        p("Samsung Daily Board", "com.samsung.android.tv.dtv",
            "Экран заставки с новостями и погодой"),
    )),

    // ─────────────────
    // VIVO / IQOO
    // ─────────────────
    ManufacturerProfile("vivo / iQOO", "📲", listOf(
        p("vivo Analytics", "com.vivo.analytics",
            "Сбор данных об использовании устройства",
            priority = true),
        p("User Experience Program", "com.vivo.abe",
            "Программа улучшения продуктов vivo (сбор данных)",
            priority = true),
        p("Hot Apps", "com.vivo.hotapps",
            "Рекомендации популярных приложений",
            priority = true),
        p("Hot Games", "com.vivo.hotgames",
            "Рекомендации популярных игр",
            priority = true),
        p("App Recommendation", "com.vivo.recommend",
            "Фоновый сервис рекомендаций приложений",
            priority = true),
        p("Crash Report", "com.vivo.crashreport",
            "Отправка отчётов об ошибках в vivo",
            priority = true),
        p("vivo Feedback", "com.vivo.feedback",
            "Отправка отзывов в vivo",
            priority = true),
        p("Browser News", "com.vivo.browser.news",
            "Новостная лента в браузере vivo",
            priority = true),
        p("vivo Browser", "com.vivo.browser",
            "Встроенный браузер vivo"),
        p("Jovi (ассистент)", "com.vivo.jovi",
            "AI-ассистент vivo",
            OptimizationRisk.MEDIUM),
        p("V-Appstore", "com.bbk.appstore",
            "Магазин приложений vivo"),
        p("EasyShare", "com.vivo.easyshare",
            "Обмен файлами между устройствами vivo"),
        p("vivoCloud", "com.vivo.cloud",
            "Облачное хранилище vivo",
            OptimizationRisk.MEDIUM),
        p("AI Engine", "com.vivo.aiengine",
            "AI-функции прошивки — частично затрагивает умную камеру",
            OptimizationRisk.MEDIUM),
        p("Browser Service", "com.vivo.browser.provider",
            "Фоновый сервис браузера vivo"),
        p("vivo Pay", "com.vivo.pay",
            "Платёжный сервис vivo Pay"),
        p("Live Wallpaper", "com.vivo.livewallpaper",
            "Живые обои vivo с серверными загрузками"),
        p("App Store Statistics", "com.vivo.appstore.statistics",
            "Статистика использования магазина приложений"),
        p("Search Service", "com.vivo.search",
            "Глобальный поиск vivo"),
    )),

    // ─────────────────
    // REALME / OPPO
    // ─────────────────
    ManufacturerProfile("realme / OPPO", "🔶", listOf(
        p("HeyTap Analytics", "com.heytap.statistics",
            "Аналитика и идентификатор пользователя в экосистеме HeyTap",
            priority = true),
        p("OPPO/realme UX Program", "com.oplus.statistics",
            "Программа сбора данных об использовании",
            priority = true),
        p("Hot Apps", "com.oppo.hotapps",
            "Рекомендации популярных приложений",
            priority = true),
        p("Hot Games", "com.oppo.hotgames",
            "Рекомендации популярных игр",
            priority = true),
        p("App Recommendation", "com.oppo.recommend",
            "Фоновый сервис рекомендаций",
            priority = true),
        p("HeyTap Feedback", "com.heytap.feedback",
            "Отправка отзывов в HeyTap/OPPO",
            priority = true),
        p("Discover (реклама)", "com.heytap.discovery",
            "Рекламная лента HeyTap в браузере и магазине",
            priority = true),
        p("HeyTap Cloud", "com.heytap.cloud",
            "Облачный сервис OPPO/realme",
            OptimizationRisk.MEDIUM),
        p("HeyTap Browser", "com.heytap.browser",
            "Встроенный браузер ColorOS"),
        p("Game Space", "com.oppo.gamespace",
            "Игровой режим OPPO/realme",
            OptimizationRisk.MEDIUM),
        p("App Market (HeyTap)", "com.heytap.market",
            "Магазин приложений HeyTap/OPPO"),
        p("Theme Store", "com.coloros.themestore",
            "Магазин тем ColorOS"),
        p("Smart Assistant (Breeno)", "com.oplus.assistant",
            "AI-ассистент Breeno",
            OptimizationRisk.MEDIUM),
        p("Smart Sidebar", "com.coloros.smartsidebar",
            "Умная боковая панель с рекомендациями"),
        p("ORoaming", "com.coloros.oroaming",
            "Сервис роуминга OPPO"),
        p("Video Center", "com.heytap.mcs",
            "Видеосервис HeyTap"),
        p("Music Center", "com.coloros.music",
            "Музыкальный сервис ColorOS"),
        p("Clone Phone", "com.coloros.clonephone",
            "Перенос данных с другого телефона"),
        p("realme Community", "com.realme.community",
            "Сообщество пользователей realme"),
        p("ColorOS Feedback", "com.coloros.feedback",
            "Отправка отзывов о ColorOS"),
        p("OPPO Pay", "com.oppo.pay",
            "Платёжный сервис OPPO Pay"),
    )),

    // ─────────────────
    // ONEPLUS
    // ─────────────────
    ManufacturerProfile("OnePlus (OxygenOS)", "🔷", listOf(
        p("OnePlus Analytics", "com.oneplus.statistics",
            "Сбор данных об использовании устройства OnePlus",
            priority = true),
        p("User Experience Program", "com.oneplus.opbugreportlite",
            "Программа улучшения OxygenOS (сбор данных)",
            priority = true),
        p("Hot Apps", "com.oplus.hotapps",
            "Рекомендации популярных приложений",
            priority = true),
        p("Hot Games", "com.oplus.hotgames",
            "Рекомендации популярных игр",
            priority = true),
        p("App Recommendation", "com.oplus.recommend",
            "Фоновый сервис рекомендаций",
            priority = true),
        p("OnePlus Community", "com.oneplus.community",
            "Сообщество пользователей OnePlus — постоянно в фоне",
            priority = true),
        p("OnePlus Feedback", "com.oneplus.feedback",
            "Отправка отзывов в OnePlus",
            priority = true),
        p("Crash Report", "com.oneplus.crashreport",
            "Отправка отчётов об ошибках",
            priority = true),
        p("OnePlus Store", "com.oneplus.store",
            "Магазин аксессуаров OnePlus"),
        p("OnePlus Cloud", "com.oneplus.cloud",
            "Облачный сервис OnePlus",
            OptimizationRisk.MEDIUM),
        p("Shelf", "net.oneplus.launcher",
            "Рабочий стол и «полка» OnePlus с рекомендациями",
            OptimizationRisk.MEDIUM),
        p("OnePlus Scout", "com.oneplus.globalSearch",
            "Глобальный поиск по устройству"),
        p("OnePlus Weather", "com.oneplus.weather",
            "Погодное приложение OnePlus"),
        p("OnePlus Health", "com.oneplus.health",
            "Трекер здоровья OnePlus"),
        p("Game Space (OnePlus)", "com.oneplus.gamespace",
            "Игровой режим OxygenOS",
            OptimizationRisk.MEDIUM),
        p("OxygenOS Tips", "com.oneplus.tips",
            "Советы по использованию OxygenOS"),
        p("OnePlus Browser", "com.heytap.browser",
            "Браузер от HeyTap на устройствах OnePlus"),
        p("Smart Assistant (OPLUS)", "com.oplus.assistant",
            "AI-ассистент OxygenOS",
            OptimizationRisk.MEDIUM),
    )),

    // ─────────────────
    // INFINIX / TECNO (XOS / HiOS)
    // ─────────────────
    ManufacturerProfile("Infinix / Tecno", "📟", listOf(
        p("Transsion Analytics", "com.transsion.analytics",
            "Сбор данных об использовании устройства",
            priority = true),
        p("User Experience Program", "com.transsion.statistics",
            "Программа улучшения XOS/HiOS (сбор данных)",
            priority = true),
        p("Hot Apps", "com.transsion.hotapps",
            "Рекомендации популярных приложений",
            priority = true),
        p("Hot Games", "com.transsion.hotgames",
            "Рекомендации популярных игр",
            priority = true),
        p("App Recommendation", "com.transsion.recommend",
            "Фоновый сервис рекомендаций",
            priority = true),
        p("CarlCare", "com.transsion.carlcare",
            "Сервисное приложение с телеметрией и удалённой диагностикой",
            priority = true),
        p("Crash Report", "com.transsion.crashreport",
            "Отправка отчётов об ошибках",
            priority = true),
        p("Feedback", "com.transsion.feedback",
            "Отправка отзывов в Transsion",
            priority = true),
        p("Palstore (AppStore)", "com.transsion.appstore",
            "Магазин приложений Transsion"),
        p("Boomplay Music", "com.transsion.boomplay",
            "Музыкальный стриминговый сервис"),
        p("XCloud", "com.transsion.cloud",
            "Облачный сервис Transsion",
            OptimizationRisk.MEDIUM),
        p("Phoenix Browser", "com.transsion.browser",
            "Браузер Transsion"),
        p("XOS Launcher Stats", "com.transsion.launcherstatics",
            "Статистика использования лаунчера"),
        p("Games Center", "com.transsion.gamecenter",
            "Игровой центр Transsion"),
        p("Transsion Theme Store", "com.transsion.themestore",
            "Магазин тем XOS/HiOS"),
        p("Smart Panel", "com.transsion.smartpanel",
            "Умная боковая панель"),
        p("EasyShare (Transsion)", "com.transsion.easyshare",
            "Обмен файлами между устройствами Transsion"),
    )),

    // ─────────────────
    // LENOVO (ZUI)
    // ─────────────────
    ManufacturerProfile("Lenovo (ZUI)", "💼", listOf(
        p("Lenovo Analytics", "com.lenovo.analytics",
            "Сбор данных об использовании устройства",
            priority = true),
        p("User Experience Program", "com.lenovo.statistics",
            "Программа улучшения ZUI (сбор данных)",
            priority = true),
        p("Hot Apps", "com.lenovo.hotapps",
            "Рекомендации популярных приложений",
            priority = true),
        p("Hot Games", "com.lenovo.hotgames",
            "Рекомендации популярных игр",
            priority = true),
        p("App Recommendation", "com.lenovo.recommend",
            "Фоновый сервис рекомендаций",
            priority = true),
        p("Lenovo Feedback", "com.lenovo.feedback",
            "Отправка отзывов в Lenovo",
            priority = true),
        p("Crash Report", "com.lenovo.crashreport",
            "Отправка отчётов об ошибках",
            priority = true),
        p("Lenovo Cloud", "com.lenovo.cloud",
            "Облачный сервис Lenovo",
            OptimizationRisk.MEDIUM),
        p("Lenovo App Store", "com.lenovo.lsf.pkg",
            "Магазин приложений Lenovo"),
        p("Lenovo Browser", "com.lenovo.browser",
            "Встроенный браузер Lenovo"),
        p("Lenovo Pay", "com.lenovo.pay",
            "Платёжный сервис Lenovo Pay"),
        p("Lenovo Health", "com.lenovo.health",
            "Трекер здоровья Lenovo"),
        p("ZUI Theme Store", "com.zui.themestore",
            "Магазин тем ZUI"),
        p("Lenovo Music", "com.lenovo.music",
            "Музыкальный плеер Lenovo"),
        p("Smart Cast", "com.lenovo.smartcast",
            "Трансляция экрана на телевизор"),
        p("Lenovo Smart Assistant", "com.lenovo.voiceassist",
            "Голосовой ассистент ZUI",
            OptimizationRisk.MEDIUM),
        p("ZUI Tips", "com.zui.tips",
            "Советы по использованию ZUI"),
    )),
)
